export const paths: { [key: string]: string } = {
  index: '/',
  homepage: '/',
  articles: '/articles',
  readArticle: '/readArticle',
  pages: '/pages',
  pricing: '/pricing',
  about: '/about',
  contactus: '/contactus',
  register: '/register',
  forgotPassword: '/forgotPassword',
  login: '/login',
  resetPassword: '/resetPassword',
  profile: '/profile',
  admin: '/admin',
  comments: 'comments',
  newpost: 'newpost',
};
